name: chaos
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - numpy=1.21.*
  - python=3.9.7
  - pytorch=1.11.0=py3.9_cuda11.3_cudnn8.2.0_0
  - pytorch-mutex=1.0=cuda
  - scikit-learn=1.0.2
  - matplotlib=3.5.1
  - pip=21.2.4
  - scipy=1.7.3
  - openpyxl=3.1.2
  - pip:
    - seasonal==0.3.1
    - tensorboard==2.9.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
